//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallLeague
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using FootBallLeague.Models;
    
    public partial class FIFAEntities : DbContext
    {
        public FIFAEntities()
            : base("name=FIFAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FootBallLeague> FootBallLeagues { get; set; }
        public virtual DbSet<Match_View> Match_View { get; set; }
    
        public virtual ObjectResult<spGetFootBallLeague_Result> spGetFootBallLeague()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetFootBallLeague_Result>("spGetFootBallLeague");
        }
    }
}
