//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_View
    {
        public string TeamName1 { get; set; }
        public string TeamName2 { get; set; }
    }
}
